// // 6502 disassembler
// n. landsteiner, mass:werk / electronic tradion 2005; e-tradion.net
// http://www.masswerk.at/6502/disassembler.html
//
// Modified by Cesar Miquel
//

var App = (function (my, $) {

  var instruction_set = {
    "00": { "opcode": "00", "desc": "NOP", "operand_size": "0", "cycles": "1" },
    "01": { "opcode": "01", "desc": "LD  BC,d16", "operand_size": "2", "cycles": "3" },
    "02": { "opcode": "02", "desc": "LD  (BC),A", "operand_size": "0", "cycles": "2" },
    "03": { "opcode": "03", "desc": "INC  BC", "operand_size": "0", "cycles": "2" },
    "04": { "opcode": "04", "desc": "INC  B", "operand_size": "0", "cycles": "1" },
    "05": { "opcode": "05", "desc": "DEC  B", "operand_size": "0", "cycles": "1" },
    "06": { "opcode": "06", "desc": "LD  B,d8", "operand_size": "1", "cycles": "2" },
    "07": { "opcode": "07", "desc": "RLCA", "operand_size": "0", "cycles": "1" },
    "08": { "opcode": "08", "desc": "LD  (a16),SP", "operand_size": "2", "cycles": "5" },
    "09": { "opcode": "09", "desc": "ADD  HL,BC", "operand_size": "0", "cycles": "2" },
    "0a": { "opcode": "0a", "desc": "LD  A,(BC)", "operand_size": "0", "cycles": "2" },
    "0b": { "opcode": "0b", "desc": "DEC  BC", "operand_size": "0", "cycles": "2" },
    "0c": { "opcode": "0c", "desc": "INC  C", "operand_size": "0", "cycles": "1" },
    "0d": { "opcode": "0d", "desc": "DEC  C", "operand_size": "0", "cycles": "1" },
    "0e": { "opcode": "0e", "desc": "LD  C,d8", "operand_size": "1", "cycles": "2" },
    "0f": { "opcode": "0f", "desc": "RRCA", "operand_size": "0", "cycles": "1" },
    "10": { "opcode": "10", "desc": "STOP", "operand_size": "1", "cycles": "0" },
    "11": { "opcode": "11", "desc": "LD  DE,d16", "operand_size": "2", "cycles": "3" },
    "12": { "opcode": "12", "desc": "LD  (DE),A", "operand_size": "0", "cycles": "2" },
    "13": { "opcode": "13", "desc": "INC  DE", "operand_size": "0", "cycles": "2" },
    "14": { "opcode": "14", "desc": "INC  D", "operand_size": "0", "cycles": "1" },
    "15": { "opcode": "15", "desc": "DEC  D", "operand_size": "0", "cycles": "1" },
    "16": { "opcode": "16", "desc": "LD  D,d8", "operand_size": "1", "cycles": "2" },
    "17": { "opcode": "17", "desc": "RLA", "operand_size": "0", "cycles": "1" },
    "18": { "opcode": "18", "desc": "JR  r8", "operand_size": "1", "cycles": "3" },
    "19": { "opcode": "19", "desc": "ADD  HL,DE", "operand_size": "0", "cycles": "2" },
    "1a": { "opcode": "1a", "desc": "LD  A,(DE)", "operand_size": "0", "cycles": "2" },
    "1b": { "opcode": "1b", "desc": "DEC  DE", "operand_size": "0", "cycles": "2" },
    "1c": { "opcode": "1c", "desc": "INC  E", "operand_size": "0", "cycles": "1" },
    "1d": { "opcode": "1d", "desc": "DEC  E", "operand_size": "0", "cycles": "1" },
    "1e": { "opcode": "1e", "desc": "LD E,d8", "operand_size": "1", "cycles": "2" },
    "1f": { "opcode": "1f", "desc": "RRA", "operand_size": "0", "cycles": "1" },
    "20": { "opcode": "20", "desc": "JR  NZ,r8", "operand_size": "1", "cycles": "0" },
    "21": { "opcode": "21", "desc": "LD  HL,d16", "operand_size": "2", "cycles": "3" },
    "22": { "opcode": "22", "desc": "LD  (HL+),A", "operand_size": "0", "cycles": "2" },
    "23": { "opcode": "23", "desc": "INC  HL", "operand_size": "0", "cycles": "2" },
    "24": { "opcode": "24", "desc": "INC  H", "operand_size": "0", "cycles": "1" },
    "25": { "opcode": "25", "desc": "DEC  H", "operand_size": "0", "cycles": "1" },
    "26": { "opcode": "26", "desc": "LD H,d8", "operand_size": "1", "cycles": "2" },
    "27": { "opcode": "27", "desc": "DAA", "operand_size": "0", "cycles": "1" },
    "28": { "opcode": "28", "desc": "JR  Z,r8", "operand_size": "1", "cycles": "0" },
    "29": { "opcode": "29", "desc": "ADD  HL,HL", "operand_size": "0", "cycles": "2" },
    "2a": { "opcode": "2a", "desc": "LD  A,(HL+)", "operand_size": "0", "cycles": "2" },
    "2b": { "opcode": "2b", "desc": "DEC  HL", "operand_size": "0", "cycles": "2" },
    "2c": { "opcode": "2c", "desc": "INC  L", "operand_size": "0", "cycles": "1" },
    "2d": { "opcode": "2d", "desc": "DEC  L", "operand_size": "0", "cycles": "1" },
    "2e": { "opcode": "2e", "desc": "LD L,d8", "operand_size": "1", "cycles": "2" },
    "2f": { "opcode": "2f", "desc": "CPL", "operand_size": "0", "cycles": "1" },
    "30": { "opcode": "30", "desc": "JR  NC,r8", "operand_size": "1", "cycles": "0" },
    "31": { "opcode": "31", "desc": "LD SP,d16", "operand_size": "2", "cycles": "3" },
    "32": { "opcode": "32", "desc": "LD  (HL-),A", "operand_size": "0", "cycles": "2" },
    "33": { "opcode": "33", "desc": "INC  SP", "operand_size": "0", "cycles": "2" },
    "34": { "opcode": "34", "desc": "INC  (HL)", "operand_size": "0", "cycles": "3" },
    "35": { "opcode": "35", "desc": "DEC  (HL)", "operand_size": "0", "cycles": "3" },
    "36": { "opcode": "36", "desc": "LD  (HL),d8", "operand_size": "1", "cycles": "3" },
    "37": { "opcode": "37", "desc": "SCF", "operand_size": "0", "cycles": "1" },
    "38": { "opcode": "38", "desc": "JR  C,r8", "operand_size": "1", "cycles": "0" },
    "39": { "opcode": "39", "desc": "ADD  HL,SP", "operand_size": "0", "cycles": "2" },
    "3a": { "opcode": "3a", "desc": "LD  A,(HL-)", "operand_size": "0", "cycles": "2" },
    "3b": { "opcode": "3b", "desc": "DEC  SP", "operand_size": "0", "cycles": "2" },
    "3c": { "opcode": "3c", "desc": "INC  A", "operand_size": "0", "cycles": "1" },
    "3d": { "opcode": "3d", "desc": "DEC  A", "operand_size": "0", "cycles": "1" },
    "3e": { "opcode": "3e", "desc": "LD  A,d8", "operand_size": "1", "cycles": "2" },
    "3f": { "opcode": "3f", "desc": "CCF", "operand_size": "0", "cycles": "1" },
    "40": { "opcode": "40", "desc": "LD  B,B", "operand_size": "0", "cycles": "1" },
    "41": { "opcode": "41", "desc": "LD  B,C", "operand_size": "0", "cycles": "1" },
    "42": { "opcode": "42", "desc": "LD  B,D", "operand_size": "0", "cycles": "1" },
    "43": { "opcode": "43", "desc": "LD  B,E", "operand_size": "0", "cycles": "1" },
    "44": { "opcode": "44", "desc": "LD  B,H", "operand_size": "0", "cycles": "1" },
    "45": { "opcode": "45", "desc": "LD  B,L", "operand_size": "0", "cycles": "1" },
    "46": { "opcode": "46", "desc": "LD  B,(HL)", "operand_size": "0", "cycles": "2" },
    "47": { "opcode": "47", "desc": "LD  B,A", "operand_size": "0", "cycles": "1" },
    "48": { "opcode": "48", "desc": "LD  C,B", "operand_size": "0", "cycles": "1" },
    "49": { "opcode": "49", "desc": "LD  C,C", "operand_size": "0", "cycles": "1" },
    "4a": { "opcode": "4a", "desc": "LD  C,D", "operand_size": "0", "cycles": "1" },
    "4b": { "opcode": "4b", "desc": "LD  C,E", "operand_size": "0", "cycles": "1" },
    "4c": { "opcode": "4c", "desc": "LD  C,H", "operand_size": "0", "cycles": "1" },
    "4d": { "opcode": "4d", "desc": "LD  C,L", "operand_size": "0", "cycles": "1" },
    "4e": { "opcode": "4e", "desc": "LD  C,(HL)", "operand_size": "0", "cycles": "2" },
    "4f": { "opcode": "4f", "desc": "LD  C,A", "operand_size": "0", "cycles": "1" },
    "50": { "opcode": "50", "desc": "LD  D,B", "operand_size": "0", "cycles": "1" },
    "51": { "opcode": "51", "desc": "LD  D,C", "operand_size": "0", "cycles": "1" },
    "52": { "opcode": "52", "desc": "LD  D,D", "operand_size": "0", "cycles": "1" },
    "53": { "opcode": "53", "desc": "LD  D,E", "operand_size": "0", "cycles": "1" },
    "54": { "opcode": "54", "desc": "LD  D,H", "operand_size": "0", "cycles": "1" },
    "55": { "opcode": "55", "desc": "LD  D,L", "operand_size": "0", "cycles": "1" },
    "56": { "opcode": "56", "desc": "LD  D,(HL)", "operand_size": "0", "cycles": "2" },
    "57": { "opcode": "57", "desc": "LD  D,A", "operand_size": "0", "cycles": "1" },
    "58": { "opcode": "58", "desc": "LD  E,B", "operand_size": "0", "cycles": "1" },
    "59": { "opcode": "59", "desc": "LD  E,C", "operand_size": "0", "cycles": "1" },
    "5a": { "opcode": "5a", "desc": "LD  E,D", "operand_size": "0", "cycles": "1" },
    "5b": { "opcode": "5b", "desc": "LD  E,E", "operand_size": "0", "cycles": "1" },
    "5c": { "opcode": "5c", "desc": "LD  E,H", "operand_size": "0", "cycles": "1" },
    "5d": { "opcode": "5d", "desc": "LD  E,L", "operand_size": "0", "cycles": "1" },
    "5e": { "opcode": "5e", "desc": "LD  E,(HL)", "operand_size": "0", "cycles": "2" },
    "5f": { "opcode": "5f", "desc": "LD  E,A", "operand_size": "0", "cycles": "1" },
    "60": { "opcode": "60", "desc": "LD  H,B", "operand_size": "0", "cycles": "1" },
    "61": { "opcode": "61", "desc": "LD  H,C", "operand_size": "0", "cycles": "1" },
    "62": { "opcode": "62", "desc": "LD  H,D", "operand_size": "0", "cycles": "1" },
    "63": { "opcode": "63", "desc": "LD  H,E", "operand_size": "0", "cycles": "1" },
    "64": { "opcode": "64", "desc": "LD  H,H", "operand_size": "0", "cycles": "1" },
    "65": { "opcode": "65", "desc": "LD  H,L", "operand_size": "0", "cycles": "1" },
    "66": { "opcode": "66", "desc": "LD  H,(HL)", "operand_size": "0", "cycles": "2" },
    "67": { "opcode": "67", "desc": "LD  H,A", "operand_size": "0", "cycles": "1" },
    "68": { "opcode": "68", "desc": "LD  L,B", "operand_size": "0", "cycles": "1" },
    "69": { "opcode": "69", "desc": "LD  L,C", "operand_size": "0", "cycles": "1" },
    "6a": { "opcode": "6a", "desc": "LD  L,D", "operand_size": "0", "cycles": "1" },
    "6b": { "opcode": "6b", "desc": "LD  L,E", "operand_size": "0", "cycles": "1" },
    "6c": { "opcode": "6c", "desc": "LD  L,H", "operand_size": "0", "cycles": "1" },
    "6d": { "opcode": "6d", "desc": "LD  L,L", "operand_size": "0", "cycles": "1" },
    "6e": { "opcode": "6e", "desc": "LD  L,(HL)", "operand_size": "0", "cycles": "2" },
    "6f": { "opcode": "6f", "desc": "LD  L,A", "operand_size": "0", "cycles": "1" },
    "70": { "opcode": "70", "desc": "LD  (HL),B", "operand_size": "0", "cycles": "2" },
    "71": { "opcode": "71", "desc": "LD  (HL),C", "operand_size": "0", "cycles": "2" },
    "72": { "opcode": "72", "desc": "LD  (HL),D", "operand_size": "0", "cycles": "2" },
    "73": { "opcode": "73", "desc": "LD  (HL),E", "operand_size": "0", "cycles": "2" },
    "74": { "opcode": "74", "desc": "LD  (HL),H", "operand_size": "0", "cycles": "2" },
    "75": { "opcode": "75", "desc": "LD  (HL),L", "operand_size": "0", "cycles": "2" },
    "76": { "opcode": "76", "desc": "HALT", "operand_size": "0", "cycles": "0" },
    "77": { "opcode": "77", "desc": "LD  (HL),A", "operand_size": "0", "cycles": "2" },
    "78": { "opcode": "78", "desc": "LD  A,B", "operand_size": "0", "cycles": "1" },
    "79": { "opcode": "79", "desc": "LD  A,C", "operand_size": "0", "cycles": "1" },
    "7a": { "opcode": "7a", "desc": "LD  A,D", "operand_size": "0", "cycles": "1" },
    "7b": { "opcode": "7b", "desc": "LD  A,E", "operand_size": "0", "cycles": "1" },
    "7c": { "opcode": "7c", "desc": "LD  A,H", "operand_size": "0", "cycles": "1" },
    "7d": { "opcode": "7d", "desc": "LD  A,L", "operand_size": "0", "cycles": "1" },
    "7e": { "opcode": "7e", "desc": "LD  A,(HL)", "operand_size": "0", "cycles": "2" },
    "7f": { "opcode": "7f", "desc": "LD  A,A", "operand_size": "0", "cycles": "1" },
    "80": { "opcode": "80", "desc": "ADD  A,B", "operand_size": "0", "cycles": "1" },
    "81": { "opcode": "81", "desc": "ADD  A,C", "operand_size": "0", "cycles": "1" },
    "82": { "opcode": "82", "desc": "ADD  A,D", "operand_size": "0", "cycles": "1" },
    "83": { "opcode": "83", "desc": "ADD  A,E", "operand_size": "0", "cycles": "1" },
    "84": { "opcode": "84", "desc": "ADD  A,H", "operand_size": "0", "cycles": "1" },
    "85": { "opcode": "85", "desc": "ADD  A,L", "operand_size": "0", "cycles": "1" },
    "86": { "opcode": "86", "desc": "ADD  A,(HL)", "operand_size": "0", "cycles": "2" },
    "87": { "opcode": "87", "desc": "ADD  A,A", "operand_size": "0", "cycles": "1" },
    "88": { "opcode": "88", "desc": "ADC  A,B", "operand_size": "0", "cycles": "1" },
    "89": { "opcode": "89", "desc": "ADC  A,C", "operand_size": "0", "cycles": "1" },
    "8a": { "opcode": "8a", "desc": "ADC  A,D", "operand_size": "0", "cycles": "1" },
    "8b": { "opcode": "8b", "desc": "ADC  A,E", "operand_size": "0", "cycles": "1" },
    "8c": { "opcode": "8c", "desc": "ADC  A,H", "operand_size": "0", "cycles": "1" },
    "8d": { "opcode": "8d", "desc": "ADC  A,L", "operand_size": "0", "cycles": "1" },
    "8e": { "opcode": "8e", "desc": "ADC  A,(HL)", "operand_size": "0", "cycles": "2" },
    "8f": { "opcode": "8f", "desc": "ADC  A,A", "operand_size": "0", "cycles": "1" },
    "90": { "opcode": "90", "desc": "SUB  B", "operand_size": "0", "cycles": "1" },
    "91": { "opcode": "91", "desc": "SUB  C", "operand_size": "0", "cycles": "1" },
    "92": { "opcode": "92", "desc": "SUB  D", "operand_size": "0", "cycles": "1" },
    "93": { "opcode": "93", "desc": "SUB  E", "operand_size": "0", "cycles": "1" },
    "94": { "opcode": "94", "desc": "SUB  H", "operand_size": "0", "cycles": "1" },
    "95": { "opcode": "95", "desc": "SUB  L", "operand_size": "0", "cycles": "1" },
    "96": { "opcode": "96", "desc": "SUB  (HL)", "operand_size": "0", "cycles": "2" },
    "97": { "opcode": "97", "desc": "SUB  A", "operand_size": "0", "cycles": "1" },
    "98": { "opcode": "98", "desc": "SBC  A,B", "operand_size": "0", "cycles": "1" },
    "99": { "opcode": "99", "desc": "SBC  A,C", "operand_size": "0", "cycles": "1" },
    "9a": { "opcode": "9a", "desc": "SBC  A,D", "operand_size": "0", "cycles": "1" },
    "9b": { "opcode": "9b", "desc": "SBC  A,E", "operand_size": "0", "cycles": "1" },
    "9c": { "opcode": "9c", "desc": "SBC  A,H", "operand_size": "0", "cycles": "1" },
    "9d": { "opcode": "9d", "desc": "SBC  A,L", "operand_size": "0", "cycles": "1" },
    "9e": { "opcode": "9e", "desc": "SBC  A,(HL)", "operand_size": "0", "cycles": "2" },
    "9f": { "opcode": "9f", "desc": "SBC  A,A", "operand_size": "0", "cycles": "1" },
    "a0": { "opcode": "a0", "desc": "AND  B", "operand_size": "0", "cycles": "1" },
    "a1": { "opcode": "a1", "desc": "AND  C", "operand_size": "0", "cycles": "1" },
    "a2": { "opcode": "a2", "desc": "AND  D", "operand_size": "0", "cycles": "1" },
    "a3": { "opcode": "a3", "desc": "AND  E", "operand_size": "0", "cycles": "1" },
    "a4": { "opcode": "a4", "desc": "AND  H", "operand_size": "0", "cycles": "1" },
    "a5": { "opcode": "a5", "desc": "AND  L", "operand_size": "0", "cycles": "1" },
    "a6": { "opcode": "a6", "desc": "AND  (HL)", "operand_size": "0", "cycles": "2" },
    "a7": { "opcode": "a7", "desc": "AND  A", "operand_size": "0", "cycles": "1" },
    "a8": { "opcode": "a8", "desc": "XOR  B", "operand_size": "0", "cycles": "1" },
    "a9": { "opcode": "a9", "desc": "XOR  C", "operand_size": "0", "cycles": "1" },
    "aa": { "opcode": "aa", "desc": "XOR  D", "operand_size": "0", "cycles": "1" },
    "ab": { "opcode": "ab", "desc": "XOR  E", "operand_size": "0", "cycles": "1" },
    "ac": { "opcode": "ac", "desc": "XOR  H", "operand_size": "0", "cycles": "1" },
    "ad": { "opcode": "ad", "desc": "XOR  L", "operand_size": "0", "cycles": "1" },
    "ae": { "opcode": "ae", "desc": "XOR  (HL)", "operand_size": "0", "cycles": "2" },
    "af": { "opcode": "af", "desc": "XOR  A", "operand_size": "0", "cycles": "1" },
    "b0": { "opcode": "b0", "desc": "OR  B", "operand_size": "0", "cycles": "1" },
    "b1": { "opcode": "b1", "desc": "OR  C", "operand_size": "0", "cycles": "1" },
    "b2": { "opcode": "b2", "desc": "OR  D", "operand_size": "0", "cycles": "1" },
    "b3": { "opcode": "b3", "desc": "OR  E", "operand_size": "0", "cycles": "1" },
    "b4": { "opcode": "b4", "desc": "OR  H", "operand_size": "0", "cycles": "1" },
    "b5": { "opcode": "b5", "desc": "OR  L", "operand_size": "0", "cycles": "1" },
    "b6": { "opcode": "b6", "desc": "OR  (HL)", "operand_size": "0", "cycles": "2" },
    "b7": { "opcode": "b7", "desc": "OR  A", "operand_size": "0", "cycles": "1" },
    "b8": { "opcode": "b8", "desc": "CP  B", "operand_size": "0", "cycles": "1" },
    "b9": { "opcode": "b9", "desc": "CP  C", "operand_size": "0", "cycles": "1" },
    "ba": { "opcode": "ba", "desc": "CP  D", "operand_size": "0", "cycles": "1" },
    "bb": { "opcode": "bb", "desc": "CP  E", "operand_size": "0", "cycles": "1" },
    "bc": { "opcode": "bc", "desc": "CP  H", "operand_size": "0", "cycles": "1" },
    "bd": { "opcode": "bd", "desc": "CP  L", "operand_size": "0", "cycles": "1" },
    "be": { "opcode": "be", "desc": "CP  (HL)", "operand_size": "0", "cycles": "2" },
    "bf": { "opcode": "bf", "desc": "CP  A", "operand_size": "0", "cycles": "1" },
    "c0": { "opcode": "c0", "desc": "RET NZ", "operand_size": "0", "cycles": "0" },
    "c1": { "opcode": "c1", "desc": "POP  BC", "operand_size": "0", "cycles": "3" },
    "c2": { "opcode": "c2", "desc": "JP  NZ,a16", "operand_size": "2", "cycles": "0" },
    "c3": { "opcode": "c3", "desc": "JP  a16", "operand_size": "2", "cycles": "4" },
    "c4": { "opcode": "c4", "desc": "CALL  NZ,a16", "operand_size": "2", "cycles": "0" },
    "c5": { "opcode": "c5", "desc": "PUSH BC", "operand_size": "0", "cycles": "4" },
    "c6": { "opcode": "c6", "desc": "ADD  A,d8", "operand_size": "1", "cycles": "2" },
    "c7": { "opcode": "c7", "desc": "RST n", "operand_size": "0", "cycles": "4" },
    "c8": { "opcode": "c8", "desc": "RET Z", "operand_size": "0", "cycles": "0" },
    "c9": { "opcode": "c9", "desc": "RET", "operand_size": "0", "cycles": "4" },
    "ca": { "opcode": "ca", "desc": "JP  Z,a16", "operand_size": "2", "cycles": "0" },
    "cc": { "opcode": "cc", "desc": "CALL  Z,a16", "operand_size": "2", "cycles": "0" },
    "cd": { "opcode": "cd", "desc": "CALL a16", "operand_size": "2", "cycles": "6" },
    "ce": { "opcode": "ce", "desc": "ADC  A,d8", "operand_size": "1", "cycles": "2" },
    "cf": { "opcode": "cf", "desc": "RST n", "operand_size": "0", "cycles": "4" },
    "d0": { "opcode": "d0", "desc": "RET NC", "operand_size": "0", "cycles": "0" },
    "d1": { "opcode": "d1", "desc": "POP  DE", "operand_size": "0", "cycles": "3" },
    "d2": { "opcode": "d2", "desc": "JP  NC,a16", "operand_size": "2", "cycles": "0" },
    "d4": { "opcode": "d4", "desc": "CALL  NC,a16", "operand_size": "2", "cycles": "0" },
    "d5": { "opcode": "d5", "desc": "PUSH DE", "operand_size": "0", "cycles": "4" },
    "d6": { "opcode": "d6", "desc": "SUB  d8", "operand_size": "1", "cycles": "2" },
    "d7": { "opcode": "d7", "desc": "RST n", "operand_size": "0", "cycles": "4" },
    "d8": { "opcode": "d8", "desc": "RET C", "operand_size": "0", "cycles": "0" },
    "d9": { "opcode": "d9", "desc": "RETI", "operand_size": "0", "cycles": "4" },
    "da": { "opcode": "da", "desc": "JP  C,a16", "operand_size": "2", "cycles": "0" },
    "dc": { "opcode": "dc", "desc": "CALL  C,a16", "operand_size": "2", "cycles": "0" },
    "de": { "opcode": "de", "desc": "SBC  A,d8", "operand_size": "1", "cycles": "2" },
    "df": { "opcode": "df", "desc": "RST  n", "operand_size": "0", "cycles": "4" },
    "e0": { "opcode": "e0", "desc": "LDH  (a8),A", "operand_size": "1", "cycles": "3" },
    "e1": { "opcode": "e1", "desc": "POP  HL", "operand_size": "0", "cycles": "3" },
    "e2": { "opcode": "e2", "desc": "LD  (C),A", "operand_size": "0", "cycles": "2" },
    "e5": { "opcode": "e5", "desc": "PUSH HL", "operand_size": "0", "cycles": "4" },
    "e6": { "opcode": "e6", "desc": "AND  d8", "operand_size": "1", "cycles": "2" },
    "e7": { "opcode": "e7", "desc": "RST n", "operand_size": "0", "cycles": "4" },
    "e8": { "opcode": "e8", "desc": "ADD  SP,r8", "operand_size": "1", "cycles": "4" },
    "e9": { "opcode": "e9", "desc": "JP  (HL)", "operand_size": "0", "cycles": "1" },
    "ea": { "opcode": "ea", "desc": "LD  (a16),A", "operand_size": "2", "cycles": "4" },
    "ee": { "opcode": "ee", "desc": "XOR  d8", "operand_size": "1", "cycles": "2" },
    "ef": { "opcode": "ef", "desc": "RST n", "operand_size": "0", "cycles": "4" },
    "f0": { "opcode": "f0", "desc": "LDH  A,(a8)", "operand_size": "1", "cycles": "3" },
    "f1": { "opcode": "f1", "desc": "POP  AF", "operand_size": "0", "cycles": "3" },
    "f2": { "opcode": "f2", "desc": "LD  A,(C)", "operand_size": "0", "cycles": "2" },
    "f3": { "opcode": "f3", "desc": "DI", "operand_size": "0", "cycles": "1" },
    "f5": { "opcode": "f5", "desc": "PUSH AF", "operand_size": "0", "cycles": "4" },
    "f6": { "opcode": "f6", "desc": "OR  d8", "operand_size": "1", "cycles": "2" },
    "f7": { "opcode": "f7", "desc": "RST n", "operand_size": "0", "cycles": "4" },
    "f8": { "opcode": "f8", "desc": "LD  HL,SP+d8", "operand_size": "1", "cycles": "3" },
    "f9": { "opcode": "f9", "desc": "LD  SP,HL", "operand_size": "0", "cycles": "2" },
    "fa": { "opcode": "fa", "desc": "LD  A,(a16)", "operand_size": "2", "cycles": "4" },
    "fb": { "opcode": "fb", "desc": "EI", "operand_size": "0", "cycles": "1" },
    "fe": { "opcode": "fe", "desc": "CP  d8", "operand_size": "1", "cycles": "2" },
    "ff": { "opcode": "ff", "desc": "RST n", "operand_size": "0", "cycles": "4" }
  };

  var instruction_set_cb = {
    "00": { "opcode": "00", "desc": "RLC B", "operand_size": "0", "cycles": "2" },
    "01": { "opcode": "01", "desc": "RLC C", "operand_size": "0", "cycles": "2" },
    "02": { "opcode": "02", "desc": "RLC D", "operand_size": "0", "cycles": "2" },
    "03": { "opcode": "03", "desc": "RLC E", "operand_size": "0", "cycles": "2" },
    "04": { "opcode": "04", "desc": "RLC H", "operand_size": "0", "cycles": "2" },
    "05": { "opcode": "05", "desc": "RLC L", "operand_size": "0", "cycles": "2" },
    "06": { "opcode": "06", "desc": "RLC (HL)", "operand_size": "0", "cycles": "4" },
    "07": { "opcode": "07", "desc": "RLC A", "operand_size": "0", "cycles": "2" },
    "08": { "opcode": "08", "desc": "RRC B", "operand_size": "0", "cycles": "2" },
    "09": { "opcode": "09", "desc": "RRC C", "operand_size": "0", "cycles": "2" },
    "0a": { "opcode": "0a", "desc": "RRC D", "operand_size": "0", "cycles": "2" },
    "0b": { "opcode": "0b", "desc": "RRC E", "operand_size": "0", "cycles": "2" },
    "0c": { "opcode": "0c", "desc": "RRC H", "operand_size": "0", "cycles": "2" },
    "0d": { "opcode": "0d", "desc": "RRC L", "operand_size": "0", "cycles": "2" },
    "0e": { "opcode": "0e", "desc": "RRC (HL)", "operand_size": "0", "cycles": "4" },
    "0f": { "opcode": "0f", "desc": "RRC A", "operand_size": "0", "cycles": "2" },
    "10": { "opcode": "10", "desc": "RL B", "operand_size": "0", "cycles": "2" },
    "11": { "opcode": "11", "desc": "RL C", "operand_size": "0", "cycles": "2" },
    "12": { "opcode": "12", "desc": "RL D", "operand_size": "0", "cycles": "2" },
    "13": { "opcode": "13", "desc": "RL E", "operand_size": "0", "cycles": "2" },
    "14": { "opcode": "14", "desc": "RL H", "operand_size": "0", "cycles": "2" },
    "15": { "opcode": "15", "desc": "RL L", "operand_size": "0", "cycles": "2" },
    "16": { "opcode": "16", "desc": "RL (HL)", "operand_size": "0", "cycles": "4" },
    "17": { "opcode": "17", "desc": "RL A", "operand_size": "0", "cycles": "2" },
    "18": { "opcode": "18", "desc": "RR B", "operand_size": "0", "cycles": "2" },
    "19": { "opcode": "19", "desc": "RR C", "operand_size": "0", "cycles": "2" },
    "1a": { "opcode": "1a", "desc": "RR D", "operand_size": "0", "cycles": "2" },
    "1b": { "opcode": "1b", "desc": "RR E", "operand_size": "0", "cycles": "2" },
    "1c": { "opcode": "1c", "desc": "RR H", "operand_size": "0", "cycles": "2" },
    "1d": { "opcode": "1d", "desc": "RR L", "operand_size": "0", "cycles": "2" },
    "1e": { "opcode": "1e", "desc": "RR (HL)", "operand_size": "0", "cycles": "4" },
    "1f": { "opcode": "1f", "desc": "RR A", "operand_size": "0", "cycles": "2" },
    "20": { "opcode": "20", "desc": "SLA B", "operand_size": "0", "cycles": "2" },
    "21": { "opcode": "21", "desc": "SLA C", "operand_size": "0", "cycles": "2" },
    "22": { "opcode": "22", "desc": "SLA D", "operand_size": "0", "cycles": "2" },
    "23": { "opcode": "23", "desc": "SLA E", "operand_size": "0", "cycles": "2" },
    "24": { "opcode": "24", "desc": "SLA H", "operand_size": "0", "cycles": "2" },
    "25": { "opcode": "25", "desc": "SLA L", "operand_size": "0", "cycles": "2" },
    "26": { "opcode": "26", "desc": "SLA (HL)", "operand_size": "0", "cycles": "4" },
    "27": { "opcode": "27", "desc": "SLA A", "operand_size": "0", "cycles": "2" },
    "28": { "opcode": "28", "desc": "SRA B", "operand_size": "0", "cycles": "2" },
    "29": { "opcode": "29", "desc": "SRA C", "operand_size": "0", "cycles": "2" },
    "2a": { "opcode": "2a", "desc": "SRA D", "operand_size": "0", "cycles": "2" },
    "2b": { "opcode": "2b", "desc": "SRA E", "operand_size": "0", "cycles": "2" },
    "2c": { "opcode": "2c", "desc": "SRA H", "operand_size": "0", "cycles": "2" },
    "2d": { "opcode": "2d", "desc": "SRA L", "operand_size": "0", "cycles": "2" },
    "2e": { "opcode": "2e", "desc": "SRA (HL)", "operand_size": "0", "cycles": "4" },
    "2f": { "opcode": "2f", "desc": "SRA A", "operand_size": "0", "cycles": "2" },
    "30": { "opcode": "30", "desc": "SWAP B", "operand_size": "0", "cycles": "2" },
    "31": { "opcode": "31", "desc": "SWAP C", "operand_size": "0", "cycles": "2" },
    "32": { "opcode": "32", "desc": "SWAP D", "operand_size": "0", "cycles": "2" },
    "33": { "opcode": "33", "desc": "SWAP E", "operand_size": "0", "cycles": "2" },
    "34": { "opcode": "34", "desc": "SWAP H", "operand_size": "0", "cycles": "2" },
    "35": { "opcode": "35", "desc": "SWAP L", "operand_size": "0", "cycles": "2" },
    "36": { "opcode": "36", "desc": "SWAP (HL)", "operand_size": "0", "cycles": "4" },
    "37": { "opcode": "37", "desc": "SWAP A", "operand_size": "0", "cycles": "2" },
    "38": { "opcode": "38", "desc": "SRL B", "operand_size": "0", "cycles": "2" },
    "39": { "opcode": "39", "desc": "SRL C", "operand_size": "0", "cycles": "2" },
    "3a": { "opcode": "3a", "desc": "SRL D", "operand_size": "0", "cycles": "2" },
    "3b": { "opcode": "3b", "desc": "SRL E", "operand_size": "0", "cycles": "2" },
    "3c": { "opcode": "3c", "desc": "SRL H", "operand_size": "0", "cycles": "2" },
    "3d": { "opcode": "3d", "desc": "SRL L", "operand_size": "0", "cycles": "2" },
    "3e": { "opcode": "3e", "desc": "SRL (HL)", "operand_size": "0", "cycles": "4" },
    "3f": { "opcode": "3f", "desc": "SRL A", "operand_size": "0", "cycles": "2" },
    "40": { "opcode": "40", "desc": "BIT 0,B", "operand_size": "0", "cycles": "2" },
    "41": { "opcode": "41", "desc": "BIT 0,C", "operand_size": "0", "cycles": "2" },
    "42": { "opcode": "42", "desc": "BIT 0,D", "operand_size": "0", "cycles": "2" },
    "43": { "opcode": "43", "desc": "BIT 0,E", "operand_size": "0", "cycles": "2" },
    "44": { "opcode": "44", "desc": "BIT 0,H", "operand_size": "0", "cycles": "2" },
    "45": { "opcode": "45", "desc": "BIT 0,L", "operand_size": "0", "cycles": "2" },
    "46": { "opcode": "46", "desc": "BIT 0,(HL)", "operand_size": "0", "cycles": "3" },
    "47": { "opcode": "47", "desc": "BIT 0,A", "operand_size": "0", "cycles": "2" },
    "48": { "opcode": "48", "desc": "BIT 1,B", "operand_size": "0", "cycles": "2" },
    "49": { "opcode": "49", "desc": "BIT 1,C", "operand_size": "0", "cycles": "2" },
    "4a": { "opcode": "4a", "desc": "BIT 1,D", "operand_size": "0", "cycles": "2" },
    "4b": { "opcode": "4b", "desc": "BIT 1,E", "operand_size": "0", "cycles": "2" },
    "4c": { "opcode": "4c", "desc": "BIT 1,H", "operand_size": "0", "cycles": "2" },
    "4d": { "opcode": "4d", "desc": "BIT 1,L", "operand_size": "0", "cycles": "2" },
    "4e": { "opcode": "4e", "desc": "BIT 1,(HL)", "operand_size": "0", "cycles": "3" },
    "4f": { "opcode": "4f", "desc": "BIT 1,A", "operand_size": "0", "cycles": "2" },
    "50": { "opcode": "50", "desc": "BIT 2,B", "operand_size": "0", "cycles": "2" },
    "51": { "opcode": "51", "desc": "BIT 2,C", "operand_size": "0", "cycles": "2" },
    "52": { "opcode": "52", "desc": "BIT 2,D", "operand_size": "0", "cycles": "2" },
    "53": { "opcode": "53", "desc": "BIT 2,E", "operand_size": "0", "cycles": "2" },
    "54": { "opcode": "54", "desc": "BIT 2,H", "operand_size": "0", "cycles": "2" },
    "55": { "opcode": "55", "desc": "BIT 2,L", "operand_size": "0", "cycles": "2" },
    "56": { "opcode": "56", "desc": "BIT 2,(HL)", "operand_size": "0", "cycles": "3" },
    "57": { "opcode": "57", "desc": "BIT 2,A", "operand_size": "0", "cycles": "2" },
    "58": { "opcode": "58", "desc": "BIT 3,B", "operand_size": "0", "cycles": "2" },
    "59": { "opcode": "59", "desc": "BIT 3,C", "operand_size": "0", "cycles": "2" },
    "5a": { "opcode": "5a", "desc": "BIT 3,D", "operand_size": "0", "cycles": "2" },
    "5b": { "opcode": "5b", "desc": "BIT 3,E", "operand_size": "0", "cycles": "2" },
    "5c": { "opcode": "5c", "desc": "BIT 3,H", "operand_size": "0", "cycles": "2" },
    "5d": { "opcode": "5d", "desc": "BIT 3,L", "operand_size": "0", "cycles": "2" },
    "5e": { "opcode": "5e", "desc": "BIT 3,(HL)", "operand_size": "0", "cycles": "3" },
    "5f": { "opcode": "5f", "desc": "BIT 3,A", "operand_size": "0", "cycles": "2" },
    "60": { "opcode": "60", "desc": "BIT 4,B", "operand_size": "0", "cycles": "2" },
    "61": { "opcode": "61", "desc": "BIT 4,C", "operand_size": "0", "cycles": "2" },
    "62": { "opcode": "62", "desc": "BIT 4,D", "operand_size": "0", "cycles": "2" },
    "63": { "opcode": "63", "desc": "BIT 4,E", "operand_size": "0", "cycles": "2" },
    "64": { "opcode": "64", "desc": "BIT 4,H", "operand_size": "0", "cycles": "2" },
    "65": { "opcode": "65", "desc": "BIT 4,L", "operand_size": "0", "cycles": "2" },
    "66": { "opcode": "66", "desc": "BIT 4,(HL)", "operand_size": "0", "cycles": "3" },
    "67": { "opcode": "67", "desc": "BIT 4,A", "operand_size": "0", "cycles": "2" },
    "68": { "opcode": "68", "desc": "BIT 5,B", "operand_size": "0", "cycles": "2" },
    "69": { "opcode": "69", "desc": "BIT 5,C", "operand_size": "0", "cycles": "2" },
    "6a": { "opcode": "6a", "desc": "BIT 5,D", "operand_size": "0", "cycles": "2" },
    "6b": { "opcode": "6b", "desc": "BIT 5,E", "operand_size": "0", "cycles": "2" },
    "6c": { "opcode": "6c", "desc": "BIT 5,H", "operand_size": "0", "cycles": "2" },
    "6d": { "opcode": "6d", "desc": "BIT 5,L", "operand_size": "0", "cycles": "2" },
    "6e": { "opcode": "6e", "desc": "BIT 5,(HL)", "operand_size": "0", "cycles": "3" },
    "6f": { "opcode": "6f", "desc": "BIT 5,A", "operand_size": "0", "cycles": "2" },
    "70": { "opcode": "70", "desc": "BIT 6,B", "operand_size": "0", "cycles": "2" },
    "71": { "opcode": "71", "desc": "BIT 6,C", "operand_size": "0", "cycles": "2" },
    "72": { "opcode": "72", "desc": "BIT 6,D", "operand_size": "0", "cycles": "2" },
    "73": { "opcode": "73", "desc": "BIT 6,E", "operand_size": "0", "cycles": "2" },
    "74": { "opcode": "74", "desc": "BIT 6,H", "operand_size": "0", "cycles": "2" },
    "75": { "opcode": "75", "desc": "BIT 6,L", "operand_size": "0", "cycles": "2" },
    "76": { "opcode": "76", "desc": "BIT 6,(HL)", "operand_size": "0", "cycles": "3" },
    "77": { "opcode": "77", "desc": "BIT 6,A", "operand_size": "0", "cycles": "2" },
    "78": { "opcode": "78", "desc": "BIT 7,B", "operand_size": "0", "cycles": "2" },
    "79": { "opcode": "79", "desc": "BIT 7,C", "operand_size": "0", "cycles": "2" },
    "7a": { "opcode": "7a", "desc": "BIT 7,D", "operand_size": "0", "cycles": "2" },
    "7b": { "opcode": "7b", "desc": "BIT 7,E", "operand_size": "0", "cycles": "2" },
    "7c": { "opcode": "7c", "desc": "BIT 7,H", "operand_size": "0", "cycles": "2" },
    "7d": { "opcode": "7d", "desc": "BIT 7,L", "operand_size": "0", "cycles": "2" },
    "7e": { "opcode": "7e", "desc": "BIT 7,(HL)", "operand_size": "0", "cycles": "3" },
    "7f": { "opcode": "7f", "desc": "BIT 7,A", "operand_size": "0", "cycles": "2" },
    "80": { "opcode": "80", "desc": "RES 0,B", "operand_size": "0", "cycles": "2" },
    "81": { "opcode": "81", "desc": "RES 0,C", "operand_size": "0", "cycles": "2" },
    "82": { "opcode": "82", "desc": "RES 0,D", "operand_size": "0", "cycles": "2" },
    "83": { "opcode": "83", "desc": "RES 0,E", "operand_size": "0", "cycles": "2" },
    "84": { "opcode": "84", "desc": "RES 0,H", "operand_size": "0", "cycles": "2" },
    "85": { "opcode": "85", "desc": "RES 0,L", "operand_size": "0", "cycles": "2" },
    "86": { "opcode": "86", "desc": "RES 0,(HL)", "operand_size": "0", "cycles": "4" },
    "87": { "opcode": "87", "desc": "RES 0,A", "operand_size": "0", "cycles": "2" },
    "88": { "opcode": "88", "desc": "RES 1,B", "operand_size": "0", "cycles": "2" },
    "89": { "opcode": "89", "desc": "RES 1,C", "operand_size": "0", "cycles": "2" },
    "8a": { "opcode": "8a", "desc": "RES 1,D", "operand_size": "0", "cycles": "2" },
    "8b": { "opcode": "8b", "desc": "RES 1,E", "operand_size": "0", "cycles": "2" },
    "8c": { "opcode": "8c", "desc": "RES 1,H", "operand_size": "0", "cycles": "2" },
    "8d": { "opcode": "8d", "desc": "RES 1,L", "operand_size": "0", "cycles": "2" },
    "8e": { "opcode": "8e", "desc": "RES 1,(HL)", "operand_size": "0", "cycles": "4" },
    "8f": { "opcode": "8f", "desc": "RES 1,A", "operand_size": "0", "cycles": "2" },
    "90": { "opcode": "90", "desc": "RES 2,B", "operand_size": "0", "cycles": "2" },
    "91": { "opcode": "91", "desc": "RES 2,C", "operand_size": "0", "cycles": "2" },
    "92": { "opcode": "92", "desc": "RES 2,D", "operand_size": "0", "cycles": "2" },
    "93": { "opcode": "93", "desc": "RES 2,E", "operand_size": "0", "cycles": "2" },
    "94": { "opcode": "94", "desc": "RES 2,H", "operand_size": "0", "cycles": "2" },
    "95": { "opcode": "95", "desc": "RES 2,L", "operand_size": "0", "cycles": "2" },
    "96": { "opcode": "96", "desc": "RES 2,(HL)", "operand_size": "0", "cycles": "4" },
    "97": { "opcode": "97", "desc": "RES 2,A", "operand_size": "0", "cycles": "2" },
    "98": { "opcode": "98", "desc": "RES 3,B", "operand_size": "0", "cycles": "2" },
    "99": { "opcode": "99", "desc": "RES 3,C", "operand_size": "0", "cycles": "2" },
    "9a": { "opcode": "9a", "desc": "RES 3,D", "operand_size": "0", "cycles": "2" },
    "9b": { "opcode": "9b", "desc": "RES 3,E", "operand_size": "0", "cycles": "2" },
    "9c": { "opcode": "9c", "desc": "RES 3,H", "operand_size": "0", "cycles": "2" },
    "9d": { "opcode": "9d", "desc": "RES 3,L", "operand_size": "0", "cycles": "2" },
    "9e": { "opcode": "9e", "desc": "RES 3,(HL)", "operand_size": "0", "cycles": "4" },
    "9f": { "opcode": "9f", "desc": "RES 3,A", "operand_size": "0", "cycles": "2" },
    "a0": { "opcode": "a0", "desc": "RES 4,B", "operand_size": "0", "cycles": "2" },
    "a1": { "opcode": "a1", "desc": "RES 4,C", "operand_size": "0", "cycles": "2" },
    "a2": { "opcode": "a2", "desc": "RES 4,D", "operand_size": "0", "cycles": "2" },
    "a3": { "opcode": "a3", "desc": "RES 4,E", "operand_size": "0", "cycles": "2" },
    "a4": { "opcode": "a4", "desc": "RES 4,H", "operand_size": "0", "cycles": "2" },
    "a5": { "opcode": "a5", "desc": "RES 4,L", "operand_size": "0", "cycles": "2" },
    "a6": { "opcode": "a6", "desc": "RES 4,(HL)", "operand_size": "0", "cycles": "4" },
    "a7": { "opcode": "a7", "desc": "RES 4,A", "operand_size": "0", "cycles": "2" },
    "a8": { "opcode": "a8", "desc": "RES 5,B", "operand_size": "0", "cycles": "2" },
    "a9": { "opcode": "a9", "desc": "RES 5,C", "operand_size": "0", "cycles": "2" },
    "aa": { "opcode": "aa", "desc": "RES 5,D", "operand_size": "0", "cycles": "2" },
    "ab": { "opcode": "ab", "desc": "RES 5,E", "operand_size": "0", "cycles": "2" },
    "ac": { "opcode": "ac", "desc": "RES 5,H", "operand_size": "0", "cycles": "2" },
    "ad": { "opcode": "ad", "desc": "RES 5,L", "operand_size": "0", "cycles": "2" },
    "ae": { "opcode": "ae", "desc": "RES 5,(HL)", "operand_size": "0", "cycles": "4" },
    "af": { "opcode": "af", "desc": "RES 5,A", "operand_size": "0", "cycles": "2" },
    "b0": { "opcode": "b0", "desc": "RES 6,B", "operand_size": "0", "cycles": "2" },
    "b1": { "opcode": "b1", "desc": "RES 6,C", "operand_size": "0", "cycles": "2" },
    "b2": { "opcode": "b2", "desc": "RES 6,D", "operand_size": "0", "cycles": "2" },
    "b3": { "opcode": "b3", "desc": "RES 6,E", "operand_size": "0", "cycles": "2" },
    "b4": { "opcode": "b4", "desc": "RES 6,H", "operand_size": "0", "cycles": "2" },
    "b5": { "opcode": "b5", "desc": "RES 6,L", "operand_size": "0", "cycles": "2" },
    "b6": { "opcode": "b6", "desc": "RES 6,(HL)", "operand_size": "0", "cycles": "4" },
    "b7": { "opcode": "b7", "desc": "RES 6,A", "operand_size": "0", "cycles": "2" },
    "b8": { "opcode": "b8", "desc": "RES 7,B", "operand_size": "0", "cycles": "2" },
    "b9": { "opcode": "b9", "desc": "RES 7,C", "operand_size": "0", "cycles": "2" },
    "ba": { "opcode": "ba", "desc": "RES 7,D", "operand_size": "0", "cycles": "2" },
    "bb": { "opcode": "bb", "desc": "RES 7,E", "operand_size": "0", "cycles": "2" },
    "bc": { "opcode": "bc", "desc": "RES 7,H", "operand_size": "0", "cycles": "2" },
    "bd": { "opcode": "bd", "desc": "RES 7,L", "operand_size": "0", "cycles": "2" },
    "be": { "opcode": "be", "desc": "RES 7,(HL)", "operand_size": "0", "cycles": "4" },
    "bf": { "opcode": "bf", "desc": "RES 7,A", "operand_size": "0", "cycles": "2" },
    "c0": { "opcode": "c0", "desc": "SET 0,B", "operand_size": "0", "cycles": "2" },
    "c1": { "opcode": "c1", "desc": "SET 0,C", "operand_size": "0", "cycles": "2" },
    "c2": { "opcode": "c2", "desc": "SET 0,D", "operand_size": "0", "cycles": "2" },
    "c3": { "opcode": "c3", "desc": "SET 0,E", "operand_size": "0", "cycles": "2" },
    "c4": { "opcode": "c4", "desc": "SET 0,H", "operand_size": "0", "cycles": "2" },
    "c5": { "opcode": "c5", "desc": "SET 0,L", "operand_size": "0", "cycles": "2" },
    "c6": { "opcode": "c6", "desc": "SET 0,(HL)", "operand_size": "0", "cycles": "4" },
    "c7": { "opcode": "c7", "desc": "SET 0,A", "operand_size": "0", "cycles": "2" },
    "c8": { "opcode": "c8", "desc": "SET 1,B", "operand_size": "0", "cycles": "2" },
    "c9": { "opcode": "c9", "desc": "SET 1,C", "operand_size": "0", "cycles": "2" },
    "ca": { "opcode": "ca", "desc": "SET 1,D", "operand_size": "0", "cycles": "2" },
    "cb": { "opcode": "cb", "desc": "SET 1,E", "operand_size": "0", "cycles": "2" },
    "cc": { "opcode": "cc", "desc": "SET 1,H", "operand_size": "0", "cycles": "2" },
    "cd": { "opcode": "cd", "desc": "SET 1,L", "operand_size": "0", "cycles": "2" },
    "ce": { "opcode": "ce", "desc": "SET 1,(HL)", "operand_size": "0", "cycles": "4" },
    "cf": { "opcode": "cf", "desc": "SET 1,A", "operand_size": "0", "cycles": "2" },
    "d0": { "opcode": "d0", "desc": "SET 2,B", "operand_size": "0", "cycles": "2" },
    "d1": { "opcode": "d1", "desc": "SET 2,C", "operand_size": "0", "cycles": "2" },
    "d2": { "opcode": "d2", "desc": "SET 2,D", "operand_size": "0", "cycles": "2" },
    "d3": { "opcode": "d3", "desc": "SET 2,E", "operand_size": "0", "cycles": "2" },
    "d4": { "opcode": "d4", "desc": "SET 2,H", "operand_size": "0", "cycles": "2" },
    "d5": { "opcode": "d5", "desc": "SET 2,L", "operand_size": "0", "cycles": "2" },
    "d6": { "opcode": "d6", "desc": "SET 2,(HL)", "operand_size": "0", "cycles": "4" },
    "d7": { "opcode": "d7", "desc": "SET 2,A", "operand_size": "0", "cycles": "2" },
    "d8": { "opcode": "d8", "desc": "SET 3,B", "operand_size": "0", "cycles": "2" },
    "d9": { "opcode": "d9", "desc": "SET 3,C", "operand_size": "0", "cycles": "2" },
    "da": { "opcode": "da", "desc": "SET 3,D", "operand_size": "0", "cycles": "2" },
    "db": { "opcode": "db", "desc": "SET 3,E", "operand_size": "0", "cycles": "2" },
    "dc": { "opcode": "dc", "desc": "SET 3,H", "operand_size": "0", "cycles": "2" },
    "dd": { "opcode": "dd", "desc": "SET 3,L", "operand_size": "0", "cycles": "2" },
    "de": { "opcode": "de", "desc": "SET 3,(HL)", "operand_size": "0", "cycles": "4" },
    "df": { "opcode": "df", "desc": "SET 3,A", "operand_size": "0", "cycles": "2" },
    "e0": { "opcode": "e0", "desc": "SET 4,B", "operand_size": "0", "cycles": "2" },
    "e1": { "opcode": "e1", "desc": "SET 4,C", "operand_size": "0", "cycles": "2" },
    "e2": { "opcode": "e2", "desc": "SET 4,D", "operand_size": "0", "cycles": "2" },
    "e3": { "opcode": "e3", "desc": "SET 4,E", "operand_size": "0", "cycles": "2" },
    "e4": { "opcode": "e4", "desc": "SET 4,H", "operand_size": "0", "cycles": "2" },
    "e5": { "opcode": "e5", "desc": "SET 4,L", "operand_size": "0", "cycles": "2" },
    "e6": { "opcode": "e6", "desc": "SET 4,(HL)", "operand_size": "0", "cycles": "4" },
    "e7": { "opcode": "e7", "desc": "SET 4,A", "operand_size": "0", "cycles": "2" },
    "e8": { "opcode": "e8", "desc": "SET 5,B", "operand_size": "0", "cycles": "2" },
    "e9": { "opcode": "e9", "desc": "SET 5,C", "operand_size": "0", "cycles": "2" },
    "ea": { "opcode": "ea", "desc": "SET 5,D", "operand_size": "0", "cycles": "2" },
    "eb": { "opcode": "eb", "desc": "SET 5,E", "operand_size": "0", "cycles": "2" },
    "ec": { "opcode": "ec", "desc": "SET 5,H", "operand_size": "0", "cycles": "2" },
    "ed": { "opcode": "ed", "desc": "SET 5,L", "operand_size": "0", "cycles": "2" },
    "ee": { "opcode": "ee", "desc": "SET 5,(HL)", "operand_size": "0", "cycles": "4" },
    "ef": { "opcode": "ef", "desc": "SET 5,A", "operand_size": "0", "cycles": "2" },
    "f0": { "opcode": "f0", "desc": "SET 6,B", "operand_size": "0", "cycles": "2" },
    "f1": { "opcode": "f1", "desc": "SET 6,C", "operand_size": "0", "cycles": "2" },
    "f2": { "opcode": "f2", "desc": "SET 6,D", "operand_size": "0", "cycles": "2" },
    "f3": { "opcode": "f3", "desc": "SET 6,E", "operand_size": "0", "cycles": "2" },
    "f4": { "opcode": "f4", "desc": "SET 6,H", "operand_size": "0", "cycles": "2" },
    "f5": { "opcode": "f5", "desc": "SET 6,L", "operand_size": "0", "cycles": "2" },
    "f6": { "opcode": "f6", "desc": "SET 6,(HL)", "operand_size": "0", "cycles": "4" },
    "f7": { "opcode": "f7", "desc": "SET 6,A", "operand_size": "0", "cycles": "2" },
    "f8": { "opcode": "f8", "desc": "SET 7,B", "operand_size": "0", "cycles": "2" },
    "f9": { "opcode": "f9", "desc": "SET 7,C", "operand_size": "0", "cycles": "2" },
    "fa": { "opcode": "fa", "desc": "SET 7,D", "operand_size": "0", "cycles": "2" },
    "fb": { "opcode": "fb", "desc": "SET 7,E", "operand_size": "0", "cycles": "2" },
    "fc": { "opcode": "fc", "desc": "SET 7,H", "operand_size": "0", "cycles": "2" },
    "fd": { "opcode": "fd", "desc": "SET 7,L", "operand_size": "0", "cycles": "2" },
    "fe": { "opcode": "fe", "desc": "SET 7,(HL)", "operand_size": "0", "cycles": "4" },
    "ff": { "opcode": "ff", "desc": "SET 7,A", "operand_size": "0", "cycles": "2" }
  };

  // public functions
  // startAddr :     disassemble from (hex)
  // stopAddr  :     dissasemble to (hex)
  my.disassemble = function(inputStartAddr, inputStopAddr) {

    // disassemble
    var code = [];

    my.pc = inputStartAddr;
    while (my.pc <= inputStopAddr && my.pc <= my.endAddr) {
      line = disassembleStep();
      code.push(line);
    }
    
    var result = {
      'type': 'code',
      'start': inputStartAddr,
      'end': my.pc,
      'code': code,
    }
    return result;
  }
	
  function disassembleStep() {
    var instr, op1, op2, addr, ops, disas, adm, step;

    // get instruction and ops, inc pc
    var instr = '' + my.ByteAt(my.pc);
    instr = my.getHexByte(instr).toLowerCase();

    var addr  = my.pc;
    var ops = instr.toUpperCase() + ' '

    var current_instruction = '';
    if (instr != 'CB' && instruction_set[instr] != undefined) {
      current_instruction = instruction_set[instr];
    }
    else if (instruction_set_cb[instr] != undefined) {
      // @TODO arreglar manejo de CB que NO ANDA!
      my.pc = my.pc + 1
      instr = '' + my.ByteAt(my.pc);
      instr = my.getHexByte(instr).toLowerCase();
      ops = 'CB ' + instr.toUpperCase() + ' '
      current_instruction = instruction_set_cb[instr];
    }
    else {
      // Unknown opcode - @TODO FINISH!!
      my.pc = (my.pc + 1);
      return {
        'addr': addr,
        'ops': '',
        'instr': '???',
        'disas': ''
      };
    }

    var step  = current_instruction['operand_size'];
    step = parseInt(step, 10);
    if (step > 0) {
      op1 = my.getHexByte(my.ByteAt(my.pc + 1));
      ops += op1 + ' ';
      if (step > 1) {
        op2 = my.getHexByte(my.ByteAt(my.pc + 2));
        ops += op2 + ' ';
      }
    }

    var parts = current_instruction['desc'].replace(/\s+/g,' ').split(' ');

    var disas = parts.length > 1 ? parts[1].trim() : '';

    if (step == 1) {
      disas = disas.replace('d8', '#$' + op1);
      disas = disas.replace('a8', '$FF' + op1);

      // relative jumps
      var opv = my.ByteAt(my.pc + 1);
      var targ = my.pc + 2;
      if (opv & 128) {
        targ -= (opv ^ 255) + 1;
      } else {
        targ += opv;
      }
      var jump_address = '$' + my.getHexWord(targ);

      disas = disas.replace('r8', '$' + jump_address);
    }
    else if (step == 2) {
      disas = disas.replace('d16', '#$' + op2 + op1);
      disas = disas.replace('a16', '$' + op2 + op1);
    }

    // Add space after opreators for readability
    disas = disas.replace(',', ', ');
    disas = disas.replace('+', ' + ');

    // Increase PC for next operation
    my.pc = (my.pc + step + 1);

    return {
      'addr': addr,
      'ops': ops.trim(),
      'instr': parts[0].trim(),
      'disas': disas
    };

  }

  return my;

}(App || {}, jQuery));
